---
- name: Add experimental builds to update-crawl-stable-build.sh
  lineinfile:
    dest: "{{ crawl_dev_dir }}dgamelaunch-config/crawl-build/update-crawl-stable-build.sh"
    regexp: ^VERS_RE=.*$
    line: VERS_RE='^[0-9]+.[0-9]+|{{ experimentals | join("|") }}$'
  when: experimentals

- name: Reset experimental builds if used before
  lineinfile:
    dest: "{{ crawl_dev_dir }}dgamelaunch-config/crawl-build/update-crawl-stable-build.sh"
    regexp: ^VERS_RE=.*$
    line: VERS_RE='^[0-9]+.[0-9]+$'
  when: experimentals == False

- name: Properly setup trigger-rebuild.pl with only used versions and experimentals
  lineinfile:
    dest: "{{ crawl_dev_dir }}dgamelaunch-config/utils/trigger-rebuild.pl"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - regexp: ^(.*)do_prompt 'trunk'.*
      line: \1do_prompt 'trunk', '{{ versions | join("', '") }}', '{{ experimentals | join("', '") }}';
    - regexp: '^(.*)} elsif \(\$ver =~.*$'
      line: \1} elsif ($ver =~ /^{{ versions | join("|") }}|{{ experimentals | join("|") }}$/) {
  when: experimentals

- name: Properly setup trigger-rebuild.pl with only used versions
  lineinfile:
    dest: "{{ crawl_dev_dir }}dgamelaunch-config/utils/trigger-rebuild.pl"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - regexp: ^(.*)do_prompt 'trunk'.*
      line: \1do_prompt 'trunk', '{{ versions | join("', '") }}';
    - regexp: ^(.*)} elsif ($ver =~.*$
      line: \1} elsif ($ver =~ /^{{ versions | join("|") }}$/) {
  when: experimentals == False

- name: Properly setup init-webtiles.sh
  template:
    src: templates/init-webtiles.sh.j2
    dest: "{{ crawl_dev_dir }}dgamelaunch-config/chroot/bin/init-webtiles.sh"
    owner: crawl-dev

- name: Add dgl-banner
  template:
    src: templates/dgl-banner.j2
    dest: "{{ crawl_dev_dir }}dgamelaunch-config/chroot/data/dgl-banner"
    owner: crawl-dev
    mode: "0755"

- name: Add stable version menus
  template:
    src: templates/menu.txt.j2
    dest: "{{ crawl_dev_dir }}dgamelaunch-config/chroot/data/menus/crawl-{{ item }}.txt"
    owner: crawl-dev
  with_items: "{{ versions }}"

- name: Add stable adv version menus
  template:
    src: templates/menu_adv.txt.j2
    dest: "{{ crawl_dev_dir }}dgamelaunch-config/chroot/data/menus/crawl-{{ item }}_adv.txt"
    owner: crawl-dev
  with_items: "{{ versions }}"

- name: Add experimental version menu
  template:
    src: templates/experimental_menu.txt.j2
    dest: "{{ crawl_dev_dir }}dgamelaunch-config/chroot/data/menus/experimental.txt"
    owner: crawl-dev

- name: Add experimental adv version menu
  template:
    src: templates/experimental_adv_menu.txt.j2
    dest: "{{ crawl_dev_dir }}dgamelaunch-config/chroot/data/menus/experimental_adv.txt"
    owner: crawl-dev

- name: Add all versions to main_*
  template:
    src: templates/{{ item }}.j2
    dest: "{{ crawl_dev_dir }}dgamelaunch-config/chroot/data/menus/{{ item }}"
    owner: crawl-dev
  with_items:
    - main_admin.txt
    - main_anon.txt
    - main_user.txt
