---
- block:
  - include: configure-scripts.yml

  - name: Configure dgl-manage.conf
    lineinfile:
      dest: "{{ crawl_dev_dir }}dgamelaunch-config/dgl-manage.conf"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - regexp: '^export DGL_UID.*$'
        line: 'export DGL_UID={{ crawl_users[0].uid }}'
      - regexp: '^export DGL_SERVER.*$'
        line: 'export DGL_SERVER={{ domain }}'
      - regexp: '^export WEB_SAVEDUMP_URL=.*$'
        line: 'export WEB_SAVEDUMP_URL="{{ protocol }}{{ domain }}/morgue/"'

  - name: Configure crawl-git.conf
    lineinfile:
      dest: "{{ crawl_dev_dir }}dgamelaunch-config/crawl-git.conf"
      regexp: '^CRAWL_GIT_URL=.*$'
      line: 'CRAWL_GIT_URL=https://github.com/crawl/crawl.git'

  - name: Configure dgamelaunch.conf
    template:
      src: templates/dgamelaunch.conf.j2
      dest: "{{ crawl_dev_dir }}dgamelaunch-config/dgamelaunch.conf"

  - name: Configure config.py
    template:
      src: templates/config.py.j2
      dest: "{{ crawl_dev_dir }}dgamelaunch-config/config.py"
    register: webtiles_config
    notify: restart webtiles

  become_user: crawl-dev
  become: yes

- name: Create core directories
  file:
    path: "{{ chroot_dir }}/{{ item }}"
    owner: "{{ crawl_users.0.name }}"
    group: "{{ crawl_users.0.name }}"
    state: directory
  with_items:
    - crawl-master/webserver/run/
    - crawl-master/webserver/sockets/
    - crawl-master/webserver/templates/
    - dgldir/dumps/
    - dgldir/morgue/
    - dgldir/rcfiles/
    - dgldir/ttyrec/
    - dgldir/data/menus/
    - dgldir/inprogress/

- name: Created shared memory file
  file:
    path: "{{ chroot_dir }}dgamelaunch"
    owner: "{{ crawl_users.0.name }}"
    group: "{{ crawl_users.0.name }}"
    state: touch

- name: Creating inprogress directories for git
  file:
    path: "{{ chroot_dir }}dgldir/inprogress/crawl-{{ item }}/"
    owner: "{{ crawl_users.0.name }}"
    group: "{{ crawl_users.0.name }}"
    state: directory
  with_items:
    - git
    - git-sprint
    - git-tut
    - git-zotdef

- name: Create experimental directories
  file:
    path: "{{ chroot_dir }}dgldir/inprogress/crawl-{{ item[0] }}{{ item[1] }}/"
    owner: "{{ crawl_users.0.name }}"
    group: "{{ crawl_users.0.name }}"
    state: directory
  with_nested:
    - "{{ experimentals }}"
    - [ '', '-sprint', '-tut', '-zotdef']

- name: Create stable inprogress directories
  file:
    path: "{{ chroot_dir }}dgldir/inprogress/crawl-{{ item[0][2:] }}{{ item[1] }}/"
    owner: "{{ crawl_users.0.name }}"
    group: "{{ crawl_users.0.name }}"
    state: directory
  with_nested:
    - "{{ versions }}"
    - [ '', '-sprint', '-tut', '-zotdef']

- name: Create rcfiles directories
  file:
    path: "{{ chroot_dir }}dgldir/rcfiles/crawl-{{ item }}/"
    owner: "{{ crawl_users.0.name }}"
    group: "{{ crawl_users.0.name }}"
    state: directory
  with_items:
    - "{{ versions | union(['git']) | union(experimentals) }}"

- name: Create data directories
  file:
    path: "{{ chroot_dir }}dgldir/data/crawl-{{ item }}-settings/"
    owner: "{{ crawl_users.0.name }}"
    group: "{{ crawl_users.0.name }}"
    state: directory
  with_items:
    - "{{ versions | union(['git']) | union(experimentals) }}"

- name: Ensure crawl user has write access to /var/mail
  file:
    path: "{{ chroot_dir }}var/mail"
    state: directory
    mode: "0777"
