---
- name: Copy over dg-status.sh script
  copy:
    src: files/dgl-status.sh
    dest: "/usr/lib/cgi-bin/dgl-status.sh"
    owner: root
    group: root
    mode: 755

- name: Install inotify watcher dependencies
  cpanm: name=Linux::Inotify2

- block:
  - name: Check if lock file exists
    stat: path={{ chroot_dir }}dgldir/.crawl-inotify.lock
    register: inotify_lock

  - name: Get inotify pid
    shell: "ps aux | grep crawl-inotify-dglwhere.pl | awk '{print $2}'"
    register: inotify_pid

  - name: Set inotify pid count
    set_fact:
      inotify_pid_count: "{{ inotify_pid.stdout_lines | length }}"

  - name: Stop inotify watcher
    shell: kill -9 {{ inotify_pid.stdout_lines[0] }}
    when: inotify_pid_count != "2"

  - name: Remove inotify watcher lock-file
    file: path={{ chroot_dir }}dgldir/.crawl-inotify.lock state=absent
    when: inotify_lock.stat.exists

  - name: Start inotify watcher
    command: "{{ crawl_dev_dir }}dgamelaunch-config/bin/dgl crawl-inotify-dglwhere"

  when: webtiles_config.changed

- name: Add ssh user
  user:
    name: "{{ ssh_username }}"
    shell: /usr/local/sbin/dgamelaunch

- name: Ensure ~/.ssh exists for user
  file:
    state: directory
    path: /home/{{ ssh_username }}/.ssh/
    mode: "0775"

- name: Upload ssh keys and create authorized_keys
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0400"
    owner: "{{ ssh_username }}"
  with_items:
    - src: files/cao_key
      dest: /home/{{ ssh_username }}/.ssh/id_rsa
    - src: files/cao_key.pub
      dest: /home/{{ ssh_username }}/.ssh/id_rsa.pub
    - src: files/cao_key.pub
      dest: /home/{{ ssh_username }}/.ssh/authorized_key

- name: Add sshd_config settings
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      Match User terminal
        AllowAgentForwarding no
        AllowTcpForwarding no
        X11Forwarding no
        PasswordAuthentication no

- name: Make sure webtiles starts on boot
  service:
    name: webtiles
    enabled: yes
    state: started
  register: webtiles_service
