---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - debootstrap
    - autoconf
    - bison
    - flex
    - ncurses-dev
    - libncursesw5-dev
    - libsqlite3-dev
